name: AIM ModerMarks Games
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches: ["dc"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Last chess game from lichess.org
        uses: lowlighter/metrics@latest
        with:
          filename: chess/metrics.plugin.chess.svg
          token: NOT_NEEDED
          base: ""
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_platform: lichess.org
