name: Chess Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Chess metrics for README
        uses: lowlighter/metrics@latest
        with:
          filename: chess-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_user: modermark
          plugin_chess_platform: lichess.org
